### ISSUE TITLE
RFC class-level metric takes in account only one level of hierarchy

### ISSUE THREAD

**Issue by alexbchr** [BasLeijdekkers/MetricsReloaded#29]
RFC metric doesn't take in account if a class have more than one parent. For example, I have 3 classes: A, B and C.

- A has 2 methods
- B has 2 methods
- C has 7 methods

Inheritance goes like C <- B <- A (A inherits B that inherits C)
I get RFC = 4 for A class, however, it should equal 2 + 2 + 7 = 11. It looks like the RFC calculation only take in account one level of "parenthood".

**Comment by BasLeijdekkers** [comment]
In fact RFC as implemented in MetricsReloaded does not take into account superclasses at all and this is by design. It just consists of the number of methods in the class plus the number of unique methods called from the class. Otherwise the RFC would in many cases say more about the hierarchy then about the class under measurement. For example take a class A with RFC 50, now create a class B extending class A but do not create any methods. When superclasses are taken into account class B will have RFC 50, but be completely empty. Such highlighting of classes that do not need attention would make RFC less useful.

That said, it seems RFC in MetricsReloaded does have some problems when for example inner classes are present, then a wrong RFC for the containing class will be calculated. And it seems object construction (new expressions) is not counted. I have fixed these issues, thanks for pointing me in their direction.

If you have any compelling arguments to include inherited methods in RFC, please let me know, I might reconsider. And thank you for your report, it was useful.
